### ISSUE TITLE
More testing on covering frequency estimation required

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#106]
Running the binary example with uniform priors in the sky position I get the following error.

It looks like none of the tests actually uses sky position priors.

Priors on use:
```
theta_prior = {
    "F0": signal_parameters["F0"],
    "F1": signal_parameters["F1"],
    "F2": signal_parameters["F2"],
    "Alpha": {
        "type": "unif",
        "lower": signal_parameters["Alpha"],
        "upper": signal_parameters["Alpha"] + 0.1,
    },
    "Delta": {
        "type": "unif",
        "lower": signal_parameters["Delta"],
        "upper": signal_parameters["Delta"] + 0.1,
    },
    "asini": {"type": "unif", "lower": 9.9, "upper": 10.1},
    "period": {
        "type": "unif",
        "lower": 44.99 * 24 * 3600.0,
        "upper": 45.01 * 24 * 3600.0,
    },
    "ecc": signal_parameters["ecc"],
    "tp": {"type": "unif", "lower": 0.999 * mid_time, "upper": 1.001 * mid_time,},
    "argp": signal_parameters["argp"],
}
```

```
17:14 INFO    : Initialising Fstat arguments
17:14 INFO    : [minCoverFreq,maxCoverFreq] not provided, trying to estimate from search ranges.
XLAL Error - buildFlatSkyGrid (DopplerScan.c:819): Check failed: (dAlpha > 0) && (dDelta > 0)
XLAL Error - buildFlatSkyGrid (DopplerScan.c:819): Invalid argument
XLAL Error - XLALInitDopplerSkyScan (DopplerScan.c:200): Check failed: (skyScan->skyGrid = buildFlatSkyGrid( &(skyScan->skyRegion), init->dAlpha, init->dDelta)) != ((void *)0)
XLAL Error - XLALInitDopplerSkyScan (DopplerScan.c:200): Internal function call failed: Invalid argument
XLAL Error - XLALInitFactoredGrid (DopplerFullScan.c:326): Check failed: XLALInitDopplerSkyScan ( &(fscan->skyScan), &skyScanInit) == XLAL_SUCCESS
XLAL Error - XLALInitFactoredGrid (DopplerFullScan.c:326): Internal function call failed: Invalid argument
XLAL Error - XLALInitDopplerFullScan (DopplerFullScan.c:149): Check failed: XLALInitFactoredGrid ( thisScan, init ) == XLAL_SUCCESS
XLAL Error - XLALInitDopplerFullScan (DopplerFullScan.c:149): Internal function call failed: Invalid argument
Traceback (most recent call last):
  File "PyFstat_example_semi_coherent_binary_search_using_MCMC.py", line 92, in <module>
    mcmc.run()
  File "/home/rodrigo/gravity/git/PyFstat/pyfstat/mcmc_based_searches.py", line 642, in run
    self._initiate_search_object()
  File "/home/rodrigo/gravity/git/PyFstat/pyfstat/mcmc_based_searches.py", line 2569, in _initiate_search_object
    self.search = core.SemiCoherentSearch(
  File "/home/rodrigo/gravity/git/PyFstat/pyfstat/helper_functions.py", line 219, in wrapper
    func(self, *args, **kargs)
  File "/home/rodrigo/gravity/git/PyFstat/pyfstat/core.py", line 1571, in __init__
    self.init_computefstatistic()
  File "/home/rodrigo/gravity/git/PyFstat/pyfstat/core.py", line 803, in init_computefstatistic
    self._set_min_max_cover_freqs()
  File "/home/rodrigo/gravity/git/PyFstat/pyfstat/core.py", line 950, in _set_min_max_cover_freqs
    self.estimate_min_max_CoverFreq(self.SFTCatalog)
  File "/home/rodrigo/gravity/git/PyFstat/pyfstat/core.py", line 1089, in estimate_min_max_CoverFreq
    scanState = lalpulsar.InitDopplerFullScan(scanInit)
RuntimeError: Internal function call failed: Invalid argument
```

**Comment by dbkeitel** [comment]
closed with #107
