### ISSUE TITLE
semi_coherent_directed_follow_up example failing

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#21]
```
23:26 INFO    : Calculating optimal setup for NstarMax=1000, Nsegs0=100
Traceback (most recent call last):
  File "examples/followup_examples/semi_coherent_directed_follow_up.py", line 86, in <module>
    axes=axes,
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/mcmc_based_searches.py", line 2799, in run
    gen_tex_table=gen_tex_table,
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/mcmc_based_searches.py", line 2662, in init_run_setup
    self.search.detector_names,
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/optimal_setup_functions.py", line 45, in get_optimal_setup
    Nsegs0, tref, minStartTime, maxStartTime, prior, detector_names
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/optimal_setup_functions.py", line 224, in get_Nstar_estimate
    ephemeris,
TypeError: in method 'ComputeSuperskyMetrics', argument 2 of type 'size_t'
```

**Comment by dbkeitel** [comment]
#27 fixes the error quoted above, but then the same example runs into another error:
```
11:03 INFO    : Calculating optimal setup for NstarMax=1000, Nsegs0=100
11:04 INFO    : Stage 0, nsegs=100, Nstar=22
11:04 INFO    : Optimization terminated successfully. with 7 evaluations
11:04 INFO    : Stage 1, nsegs=35, Nstar=182
11:04 INFO    : Optimization terminated successfully. with 8 evaluations
11:04 INFO    : Stage 2, nsegs=5, Nstar=8800
11:04 INFO    : Optimization terminated successfully. with 6 evaluations
11:05 INFO    : Stage 3, nsegs=1, Nstar=100000
Traceback (most recent call last):
  File "examples/followup_examples/semi_coherent_directed_follow_up.py", line 86, in <module>
    axes=axes,
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/mcmc_based_searches.py", line 2799, in run
    gen_tex_table=gen_tex_table,
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/mcmc_based_searches.py", line 2670, in init_run_setup
    self.theta_prior,
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/mcmc_based_searches.py", line 2596, in write_setup_input_file
    pickle.dump(d, f)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/dill/_dill.py", line 259, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/dill/_dill.py", line 445, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.7/pickle.py", line 434, in dump
    self.write(PROTO + pack("<B", self.proto))
  File "/usr/lib/python3.7/pickle.py", line 229, in write
    return self.file_write(data)
TypeError: write() argument must be str, not bytes
```
