### ISSUE TITLE
MCMC plotting: Matplotlib lock file error (from glitch example)

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#26]
@GregoryAshton I'm seeing the following from `examples/glitch_examples/standard_directed_MCMC_search_on_1_glitch.py` after #25.

The `mcmc_based_searches.py", line 639` line is from the standard MCMCSearch class, not glitch-specific, but I haven't seen this from other examples. Maybe the glitch search tries to do extra plotting right before this and then there's a race condition.

```
10:11 INFO    : Plotting temperature 0 chains
Traceback (most recent call last):
  File "examples/glitch_examples/semicoherent_glitch_robust_directed_MCMC_search_on_1_glitch.py", line 81, in <module>
    mcmc.run()
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/mcmc_based_searches.py", line 639, in run
    fig.savefig(os.path.join(self.outdir, self.label + "_walkers.png"))
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2091, in print_figure
    **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axis.py", line 1205, in draw
    renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axis.py", line 1150, in _get_tick_bboxes
    for tick in ticks if tick.label1.get_visible()],
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axis.py", line 1150, in <listcomp>
    for tick in ticks if tick.label1.get_visible()],
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/text.py", line 298, in _get_layout
    clean_line, self._fontproperties, ismath=ismath)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 201, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/texmanager.py", line 335, in make_dvi
    with cbook._lock_path(texfile):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 1916, in _lock_path
    lock_path))
TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
    /home/dkeitel/.cache/matplotlib/tex.cache/4b0dae8a389f557a2ad78f479c3dbb85.tex.matplotlib-lock
This maybe due to another process holding this lock file.  If you are sure no
other Matplotlib process is running, remove this file and try again.
```

**Comment by dbkeitel** [comment]
I can't reproduce this again at the moment. I've seen similar errors on a different project, they just seem to be sporadic and not really specific to certain code features. Maybe doing `plt.close()` more aggressively would help, but I'm closing this for now unless it crops up in a disruptive and/or reproducible way somewhere.

**Comment by dbkeitel** [comment]
Of course, once I close it, it crops up on another example:
```
2020-04-07 20:45:14.5891 (7501) [normal]: Search finished.
20:45 INFO    : Plotting temperature 0 chains
Traceback (most recent call last):
  File "examples/glitch_examples/semicoherent_glitch_robust_directed_MCMC_search_on_1_glitch.py", line 80, in <module>
    mcmc.run()
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/mcmc_based_searches.py", line 673, in run
    fig.savefig(os.path.join(self.outdir, self.label + "_walkers.png"))
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2091, in print_figure
    **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axis.py", line 1205, in draw
    renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axis.py", line 1150, in _get_tick_bboxes
    for tick in ticks if tick.label1.get_visible()],
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axis.py", line 1150, in <listcomp>
    for tick in ticks if tick.label1.get_visible()],
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/text.py", line 298, in _get_layout
    clean_line, self._fontproperties, ismath=ismath)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 201, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/texmanager.py", line 335, in make_dvi
    with cbook._lock_path(texfile):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 1916, in _lock_path
    lock_path))
TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
    /home/dkeitel/.cache/matplotlib/tex.cache/4b0dae8a389f557a2ad78f479c3dbb85.tex.matplotlib-lock
This maybe due to another process holding this lock file.  If you are sure no
other Matplotlib process is running, remove this file and try again.
```

It's not always on `fig.savefig()` calls, either,  I've had it on `plt.tight_layout()` too.

I wonder if it's related to system memory load or something. I definitely don't have concurrent matplotlib processes running....

**Comment by GregoryAshton** [comment]
These matplotlib errors are a real pain. I think there was some changes to matplotlib in a recent release which has exacerbated this. 

My current feeling is that for "run plots" (i.e. those created for diagnostics etc) it is most sensible to remove the plot formatting and use defaults as much as possible. This will reduce the chances for these types of error. One can then either add a "--latex" option which initializes the "pretty" plotting or, just write separate scripts for publications which look pretty. What do you think?

**Comment by dbkeitel** [comment]
Not sure if that would really help, as I've seen similar errors on other projects without, to the best of my memory, having done too much fancy styling there.

**Comment by dbkeitel** [comment]
Haven't seen this in a long time, so closing again. Maybe matplotlib has since fixed something on their side, maybe it's just a very rare corner case which we can revisit if it crops up again.
