### ISSUE TITLE
GridSearch.plot_1D() for large data sets

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#36]
@GregoryAshton while debugging examples, I ran into a matplotlib "Exceeded cell block limit" error on the `plot_1D()` calls from `examples/grid_examples/grid_search_F0F1F2.py` which has a large (but not huge, 1 million points) grid. I temporarily solved it with the recommended "agg.path.chunksize" increase, but the core issue is that your original code had a line `x = np.unique(self.data[:, xidx])` where I had to remove the `unique` to work at all for multi-dimensional grids.

Can you remember how you initially intended this to work? Was your idea to just plot the envelope of the max(2F) over the other dimensions at each unique grid point in the selected `x` dimension?

```
18:20 INFO    : Saving data to example_data/grid_search_F0F1F2/grid_search_F0F1F2_NA_GridSearch.txt
Traceback (most recent call last):
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 146, in draw_path
    self._renderer.draw_path(gc, path, transform, rgbFace)
OverflowError: In draw_path: Exceeded cell block limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/grid_examples/grid_search_F0F1F2.py", line 79, in <module>
    search.plot_1D(xkey="F2")
  File "/home/dkeitel/git/sources/PyFstat/pyfstat/grid_based_searches.py", line 341, in plot_1D
    fig.savefig(os.path.join(self.outdir, fname))
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2091, in print_figure
    **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/lines.py", line 802, in draw
    renderer.draw_path(gc, tpath, affine.frozen())
  File "/home/dkeitel/bin/venvs/pyfstat/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 148, in draw_path
    raise OverflowError("Exceeded cell block limit (set "
OverflowError: Exceeded cell block limit (set 'agg.path.chunksize' rcparam)
```

_Originally posted by @dbkeitel in https://github.com/PyFstat/PyFstat/issues/9#issuecomment-610484909_

**Comment by GregoryAshton** [comment]
@dbkeitel I'm afraid I have no memory of this. It looks just like an overly enthusiastic choice for plotting.

**Comment by dbkeitel** [comment]
Ok, thanks. I'll have to think about whether a fallback "envelope" option would be useful to implement, or just find a solution that avoids overplotting redundant points to make this more efficient.

**Comment by dbkeitel** [comment]
A clean solution would be to use [gridcorner](https://gitlab.aei.uni-hannover.de/GregAshton/gridcorner/-/blob/master/gridcorner.py)'s slicing logic, either by making a release of that package and importing from it, or by integrating those functions into PyFstat itself.
