### ISSUE TITLE
string formatting errors in examples

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#462]
`examples/transient_examples/PyFstat_example_make_data_for_[long/short]_transient_search.py` fails with 1.18.0, at least on my machine, with `TypeError: not all arguments converted during string formatting` from the `logger.info("Predicted 2F from injection Writer:", transient.predict_fstat())` lines. Before fixing (f-strings to the rescue!), I'm running an all-examples action [here](https://github.com/PyFstat/PyFstat/actions/runs/3098193884/jobs/5015796569) to see if it sees the same issue, and/or something similar in other examples.

**Comment by dbkeitel** [comment]
Strangely, that passed, even though it does encounter the same errors! -> #463

**Comment by dbkeitel** [comment]
Ok so the actions script is actually catching exceptions fine. The problem is that logging only _prints_ the error, but _does not actually raise an exception_!

And it's not at all specific to our implementation:
```
import logging
logging.info("a number:", 23)  # this prints nothing because default level is >info
logging.warning("a number:", 23)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
Message: 'a number:'
Arguments: (23,)
```
and
```
 try:
   logging.warning("a number:", 23)
 except:
   logging.error("error")
 else:
   logging.warning("success")
 
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 2, in <module>
Message: 'a number:'
Arguments: (23,)
WARNING:root:success
```
