### ISSUE TITLE
PyFstat_example_long_transient_MCMC_search.py fails

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#509]
from https://github.com/PyFstat/PyFstat/actions/runs/3549552960/jobs/5962071086 :+1: 

```
2022-11-25T16:56:58.0168896Z 22-11-25 16:56:58.010 pyfstat.utils.cli ERROR   : Execution failed: Command 'python /home/runner/work/PyFstat/PyFstat/examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py' returned non-zero exit status 1.
2022-11-25T16:56:58.0169645Z 22-11-25 16:56:58.010 pyfstat.utils.cli ERROR   : XLALComputeTransientFstatMap: encountered a single-atom Fstat-calculation. This is degenerate and cannot be computed!
2022-11-25T16:56:58.0170273Z 22-11-25 16:56:58.010 pyfstat.utils.cli ERROR   : Window-values m=0 (t0=1004320000=t0_data + 4320000), n=0 (tau=1881) ==> t1_data - t0 = 12960000
2022-11-25T16:56:58.0170884Z 22-11-25 16:56:58.010 pyfstat.utils.cli ERROR   : The most likely cause is that your t0-range covered all of your data: t0 must stay away *at least* 2*TAtom from the end of the data!
2022-11-25T16:56:58.0171507Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   : XLAL Error - XLALComputeTransientFstatMap (TransientCW_utils.c:755): Input domain error
2022-11-25T16:56:58.0171996Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   : Traceback (most recent call last):
2022-11-25T16:56:58.0173704Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py", line 94, in <module>
2022-11-25T16:56:58.0174408Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     mcmc.run(walker_plot_args={"plot_det_stat": True, "injection_parameters": inj})
2022-11-25T16:56:58.0174986Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/mcmc_based_searches.py", line 763, in run
2022-11-25T16:56:58.0175466Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     self._check_initial_points(p0)
2022-11-25T16:56:58.0176008Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/mcmc_based_searches.py", line 450, in _check_initial_points
2022-11-25T16:56:58.0176543Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     num = sum(self._evaluate_logpost(p0[nt]) == -np.inf)
2022-11-25T16:56:58.0177101Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/mcmc_based_searches.py", line 444, in _evaluate_logpost
2022-11-25T16:56:58.0177646Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     init_logl = np.array([self._logl(p, self.search) for p in p0vec])
2022-11-25T16:56:58.0178205Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/mcmc_based_searches.py", line 444, in <listcomp>
2022-11-25T16:56:58.0178738Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     init_logl = np.array([self._logl(p, self.search) for p in p0vec])
2022-11-25T16:56:58.0179280Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/mcmc_based_searches.py", line 3554, in _logl
2022-11-25T16:56:58.0179772Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     detstat = search.get_det_stat(**in_theta)
2022-11-25T16:56:58.0180307Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/core.py", line 1099, in get_fullycoherent_detstat
2022-11-25T16:56:58.0180798Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     return self.get_transient_detstats(
2022-11-25T16:56:58.0181332Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/core.py", line 1242, in get_transient_detstats
2022-11-25T16:56:58.0181893Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     self.FstatMap, self.timingFstatMap = tcw.call_compute_transient_fstat_map(
2022-11-25T16:56:58.0182503Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/tcw_fstat_map_funcs.py", line 445, in call_compute_transient_fstat_map
2022-11-25T16:56:58.0183094Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     FstatMap = fstatmap_versions[version](multiFstatAtoms, windowRange, BtSG)
2022-11-25T16:56:58.0183670Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/tcw_fstat_map_funcs.py", line 239, in <lambda>
2022-11-25T16:56:58.0184293Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     "lal": lambda multiFstatAtoms, windowRange, BtSG: lalpulsar_compute_transient_fstat_map(
2022-11-25T16:56:58.0184921Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :   File "/home/runner/work/PyFstat/PyFstat/pyfstat/tcw_fstat_map_funcs.py", line 481, in lalpulsar_compute_transient_fstat_map
2022-11-25T16:56:58.0185505Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   :     FstatMap_lalpulsar = lalpulsar.ComputeTransientFstatMap(
2022-11-25T16:56:58.0185977Z 22-11-25 16:56:58.011 pyfstat.utils.cli ERROR   : RuntimeError: Input domain error
2022-11-25T16:56:58.0186539Z 22-11-25 16:56:58.011 pyfstat INFO    : FAILED to run /home/runner/work/PyFstat/PyFstat/examples/transient_examples/PyFstat_example_long_transient_MCMC_search.py
```

**Comment by dbkeitel** [comment]
This is not a deterministic failure, as the problem is that a point `tau=1881` got drawn which is shorter than 2*Tsft=3600. (The "most likely cause" guess of the lalpulsar error message here is wrong, it's not t0 but indeed tau that's the problem.)

The weirdness is that the example clearly sets a prior
```
        "transient_duration": {
            "type": "unif",
            "lower": 2 * data.Tsft,
            "upper": data.duration - 2 * data.Tsft,
        },
```
so such a tau should never have been drawn...?

**Comment by dbkeitel** [comment]
> So the fix is to add a sanity check that the prior is actually "legal".

That would be useful too in general, but turns out that the actual underlying problem here is simply that _the implementation of halfnorm is wrong_. The pdf function `log_of_halfnorm` inside `_generic_lnprior` is correct, but `np.abs(np.random.normal(loc=kwargs["loc"], scale=kwargs["scale"]))` in `_generate_rv` is **not** in general. It's correct for loc=0, looks almost correct for large loc and scale (hence it works most of the time for the transient_duration example, but indeed sometimes leaks a bit to the left of `loc`), but becomes obviously false for small loc,scale values.

We probably should just switch to `scipy.stats`.
